[package]
name = "hax-dep1"
version = "0.1.0"
edition = "2021"

[package.metadata.hax]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hax-dep2 = { git = "https://github.com/pnmadelaine/hax-dep2" }
